### ISSUE TITLE
Whitelist for endpoints not requiring authentication

### ISSUE THREAD

**Issue by ajmyyra** [ajmyyra/ambassador-auth-oidc#5]
As an env, so we can easily return 200 to Ambassador on those endpoints that don't need authentication enabled.

**Comment by atolia** [comment]
#8

**Comment by ajmyyra** [comment]
Hi @atolia, thank you for the PR!

I'm checking this later tonight (after the NASA Mars probe broadcast :), so hopefully I can merge it in a few hours.

**Comment by ajmyyra** [comment]
This was merged on Monday and will be part of the version 1.3 available soon in Dockerhub.

**Comment by ajmyyra** [comment]
Version 1.3 with endpoint whitelisting is now available.
