### ISSUE TITLE
Possibility to return JWT token via the headers

### ISSUE THREAD

**Issue by sredbull** [ajmyyra/ambassador-auth-oidc#6]
Currently only tokens in a cookie are supported.

Will it be possible to:
- Return the JWT token via the x-auth-token header (or better named header) after login.
- Check JWT token if the x-auth-token is present.

Storing cookies to the users browsers seems unneeded in some use-cases.

**Comment by ajmyyra** [comment]
Sorry for not noticing this sooner! Cookies are certainly not always needed and this should be easily added. Let's see if I'll get it done over the weekend.

**Comment by ajmyyra** [comment]
@sredbull: Version 1.2 is now out with a possibility to access resources with X-Auth-Token header, removing the need to send cookie. During login, JWT is still only set as a cookie as the last step of authentication involves a redirect where we can't pass headers to the application. Your app can then fetch the JWT through `document.cookie`.
