### ISSUE TITLE
Version without Redis?

### ISSUE THREAD

**Issue by gmatev** [ajmyyra/ambassador-auth-oidc#9]
Have you considered an option to have this available without Redis and have the JWT token only be stored in the cookie? You will not be able to token blacklisting on logout, but this could be ok with short lived tokens and would simplify deployment?

**Comment by gmatev** [comment]
That would be fantastic. Thank you

**Comment by ajmyyra** [comment]
Version 1.3 is now out with Redis as optional. Currently logged out (blacklisted) tokens aren't cleaned automatically, so if you have millions of logouts, it's good to restart the service from time to time, but it shouldn't be a problem even with those numbers. I'll fix this thoroughly by the time 1.4 will come around.
